import './globals.css';
import MobileSidebar from './sidebarComponents/MobileSidebar';
import DesktopSidebar from './sidebarComponents/DesktopSidebar';
export const metadata = {
  title: 'Movie App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className=''>

        <MobileSidebar />
        <DesktopSidebar />
        <main className='bg-slate-200 h-screen w-screen p-4 sm:ml-48'>
          {children}
        </main>
      </body>
    </html >
  );
}