import Link from 'next/link';
import './globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ display: 'flex', minHeight: '100vh' }}>
        <aside style={{ width: '250px', padding: '20px' }}>
          <nav>
            <ul style={{ listStyleType: 'none', padding: 0 }}>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/movies">Movies</Link>
              </li>
              <li>
                <Link href="/recommend">Recommend</Link>
              </li>
            </ul>
          </nav>
        </aside>
        <main style={{ flexGrow: 1, padding: '20px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}